coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true

    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
