name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build --if-present

      - name: Run test script
        run: npm run test:verbose:coverage:codecov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        comment: #this is a top-level key
          layout: " diff, flags, files"
          behavior: default
          require_changes: false # if true: only post the comment if coverage changes
          require_base: false # [true :: must have a base report to post]
          require_head: true # [true :: must have a head report to post]
          hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]
